export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }


// src/app/product/layout.js

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" data-arp="">
//       <body>{children}</body>
//     </html>
//   );
// }

export default function ProductLayout({ children }) {
  return <>{children}</>;
}
